version: '3.3'
services:
  backend:
    container_name: "vfs_backend_service"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4848:4848"
    expose:
      - 4848
    volumes:
    - ./app:/home/app
    - ./data:/home/data